I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Тепло твоих рук\\The warmth of your hands\\game\\saves\\persistent.1740074463.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\main.py", line 666, in main
    renpy.persistent.update(True)
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\persistent.py", line 434, in update
    save()
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "C:\Users\ivant\Downloads\renpy-8.3.4-sdk\renpy\savelocation.py", line 426, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Тепло твоих рук\\The warmth of your hands\\game\\saves\\persistent.1740074463.tmp'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
The warmth of your hands 1.0
Fri Feb 21 18:04:05 2025
